version: "3.8"

services:
  susan-mariadb:
    image: mariadb:10.11
    container_name: susan-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: susan_proxy
      TZ: Asia/Taipei
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

volumes:
  mariadb_data:
