app:
  google-sheet-url: ${GOOGLE_SHEET_URL:}
  preorder-google-sheet-url: ${PREORDER_GOOGLE_SHEET_URL:https://docs.google.com/spreadsheets/d/1My6HuEGvcM9e-2rHCXMgpAPMBnuyGjQeuEvC_gDFryo/export?format=xlsx}
  standard-google-sheet-url: ${STANDARD_GOOGLE_SHEET_URL:https://docs.google.com/spreadsheets/d/1o6WQVtsjajFf2Z0mCOJKlZhOO4GfKR0y5aZhYmkucss/export?format=xlsx}
  log-sheet-names: false
  sheet-sync:
    sheet-name-match-max-compare-length: 64
    sheet-name-match-min-compare-length: 16
  admin:
    username: ${ADMIN_USERNAME:catcanfly1215}
    password: ${ADMIN_PASSWORD:Aa0425228305}

spring:
  application:
    name: susan
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3308/susan_proxy?characterEncoding=UTF-8&serverTimezone=Asia/Taipei}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: ${PORT:8080}
