spring:
  application:
    name: susan
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3308/susan_proxy?characterEncoding=UTF-8&serverTimezone=Asia/Taipei}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      # 上線穩定後改為 none 或 validate 保護資料
      ddl-auto: update
    # 在終端機印出執行的 SQL 語法，比較方便開發跟除錯
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8080
