package com.fy20047.susan.domain;

public enum ItemStatus {
    REGISTERED,
    PENDING_DEPOSIT,
    PENDING_PURCHASE,
    IN_TRANSIT,
    ARRIVED,
    SHIPPED,
    PREORDER_REGISTERED,
    PREORDER_PENDING_PURCHASE,
    PREORDER_PENDING_DEPOSIT,
    PREORDER_PURCHASED,
    PREORDER_FORWARDING,
    PREORDER_ARRIVED,
    PREORDER_SHIPPED
}
